spring:
  application:
    name: healphapp-service

  datasource:
    url: jdbc:mysql://localhost:3306/heathappservice
    username: heathappservice
    password: heathappservice
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    url: jdbc:mysql://localhost:3306/heathappservice
    user: heathappservice
    password: heathappservice
    locations: classpath:db/migration

management:
  metrics:
    tags:
      application: "${spring.application.name}"
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, prometheus, metrics"
  endpoint:
    health:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'


springdoc:
  openapi:
    title: "Helth App API"
    description: "Documentation to API"
    version: '1.0.0'
