spring:
  application:
    name: healphapp-service

  datasource:
    url: jdbc:mysql://localhost:3306/heathappservice
    username: heathappservice
    password: heathappservice
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
